spring:
  rabbitmq:
    host: 47.100.127.206
    port: 5672
    username: guest
    password: guest

  application:
    name: guest
eureka:
    instance:
      prefer-ip-address: true #注册是服务使用IP地址
    client:
        service-url:
          defaultZone: http://localhost:8761/eureka/